name: Build & Test Drupal

on: [push]

env:
  COMPOSER_MEMORY_LIMIT: -1
  SIMPLETEST_DB: sqlite://tmp/site.sqlite
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    name: "Tests | PHP ${{ matrix.php-versions }} | Drupal ${{ matrix.drupal }}"
    strategy:
      matrix:
        experimental: [false]
        php-versions:
          - "7.3"
          - "7.4"
        drupal:
          - "^8.9"
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-versions }}"
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, gd, pdo_sqlite
          
      - name: Check PHP Version
        run: |
          php -v

      - name: Update composer
        run: composer --verbose self-update --${{ matrix.composer-channel }}

      - name: Dump composer verson
        run: composer --version

      - name: Validate composer.json
        run: composer --verbose validate

      - name: Install dependencies
        run: |
          composer --verbose install
          echo "export PATH=$PATH:$GITHUB_WORKSPACE/vendor/bin" >> ~/.bash_profile
          
      - run: ./vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite

      - run: ./vendor/bin/drush runserver $SIMPLETEST_BASE_URL &

      - run: until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null

        # https://www.drupal.org/project/drupal/issues/3182653
        # https://www.drupal.org/node/3176567
      - if: ${{ matrix.php-versions == '7.4' }} || ${{ matrix.php-versions == '8.0' }}
        run: composer require phpspec/prophecy-phpunit:^2

      - name: Run a single unit test to verfiy the testing setup.
        run: ./vendor/bin/phpunit -c ./web/core ./web/core/modules/user/tests/src/Unit/UserAccessControlHandlerTest.php

      - run: ./vendor/bin/drush st
