name: Build & Test Drupal
on: [push]


jobs:
  tests:
    continue-on-error: ${{ matrix.experimental }}
    runs-on: "ubuntu-latest"
    name: "Tests | PHP ${{ matrix.php-version }} | Drupal ${{ matrix.drupal }}"
    strategy:
      matrix:
        experimental: [false]
        php-version:
          - "7.3"
          - "7.4"
        drupal:
          - "^8.9"
        include:
          - php-version: "7.2"
            drupal: "~8.9"
            experimental: false
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, gd
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: "Install dependencies"
        run: "composer install --no-progress --prefer-dist"
